
# SETUP -------------------------------------------------------------------

# essential
ukb_data_dict <- get_ukb_data_dict()
ukb_codings <- get_ukb_codings()
dummy_ukb_data_path <- download_dummy_ukb_data_to_tempdir()
dummy_ukb_data_dict <- make_data_dict(ukb_main = dummy_ukb_data_path,
                                      delim = ",",
                                      ukb_data_dict = ukb_data_dict)
dummy_ukb_data_3eid <- read_ukb(path = dummy_ukb_data_path,
                                  delim = ",",
                                  data_dict = dummy_ukb_data_dict,
                                  ukb_data_dict = ukb_data_dict,
                                  ukb_codings = ukb_codings,
                                  clean_dates = FALSE,
                                  clean_selected_continuous_and_integers = FALSE,
                                  nrows = 3)

# TESTS -------------------------------------------------------------------

# `summarise_rowise()` ----------------------------------------------------

test_that("`summarise_rowise()` returns the expected results", {
  # note, I inspected `dummy_ukb_data_3eid_bp_summarised_rowise` to check the correct results are being returned
  expect_equal(
    dummy_ukb_data_3eid_bp_summarised_rowise$mean_systolic_blood_pressure_automated_reading_4080,
    c(151.000, 143.333, 145.000),
    tolerance = 3
  )

  expect_equal(
    dummy_ukb_data_3eid_bp_summarised_rowise$sd_systolic_blood_pressure_automated_reading_4080,
    c(11.314, 13.204, 16.093),
    tolerance = 3
  )

  # see note in SETUP: this works interactively, but raises an error when testing package
  # expect_equal(
  #   dummy_ukb_data_3eid_bp_summarised_rowise$n_not_na_systolic_blood_pressure_automated_reading_4080,
  #   c(2, 3, 3),
  #   tolerance = 3
  # )
})

test_that("`summarise_rowise()` raises error if `data_dict` arg includes colnames not present in `ukb_pheno`", {
 expect_error(
   # `data_dict` includes BMI fields, but `ukb_pheno` only includes systolic BP
   dummy_ukb_data_3eid %>%
     dplyr::select(tidyselect::contains("systolic_blood_pressure")) %>%
     summarise_rowise(
       functions = c("mean", "sd", "n_not_na"),

       # data dictionary generated by make_data_dict(), filtered
       # for only numerical data
       data_dict = dummy_ukb_data_dict %>%
         dplyr::filter(.data[["FieldID"]] %in% c("4080", "21001")),

       # to summarise by FieldID
       grouping_col = "Field_FieldID",

       # additional args
       na.rm = TRUE
     ),
   regexp = "Error! `data_dict\\$descriptive_colnames` includes values not present in `names\\(ukb_pheno\\)`. Please filter `data_dict` for only the columns in `ukb_pheno` to be summarised"
 )
})

# `summarise_rowise_numerical_mean_min_max()` -----------------------------

test_that("`summarise_rowise_numerical_mean_min_max()` calculates the expected mean/min/max", {
  expect_equal(dummy_ukb_data_3eid_bmi_rowmeans$rowMeans_body_mass_index_bmi_21001,
               dummy_ukb_data_3eid_bmi_rowmeans$expected)

  expect_equal(dummy_ukb_data_3eid_bmi_pmin$pmin_body_mass_index_bmi_21001,
               dummy_ukb_data_3eid_bmi_pmin$expected)

  expect_equal(dummy_ukb_data_3eid_bmi_pmax$pmax_body_mass_index_bmi_21001,
               dummy_ukb_data_3eid_bmi_pmax$expected)
})
