---
title: "test_ukbtools"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test_ukbtools}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(ukbwranglr)
library(ukbtools)
```

# load ukbtools example data

```{r}
path_to_example_data <- system.file("extdata", package = "ukbtools")
my_ukb_data <- ukb_df("ukbxxxx", path = path_to_example_data)
```

```{r}
mapper <- ukb_df_field("ukbxxxx", path = path_to_example_data)
```

# ukbwranglr:: pheno_data_dict

```{r}
test <-
  data.table::fread(
    "/Users/alasdair/OneDrive - University College London/Lenovo backup 181219/WellcomePhD/Year2/ukbiobank/ukb_dr_gwas/data/ukb_main_filter.txt",
    colClasses = c('character'),
    na.strings = c("", "NA"),
    sep = "\t",
    header = TRUE,
    data.table = TRUE,
    showProgress = TRUE,
    nrows=0
  )

test <- names(test)

test_dict <- data.table::fread("https://biobank.ctsu.ox.ac.uk/~bbdatan/Data_Dictionary_Showcase.tsv", colClasses = c("character"))

data_dict <- pheno_data_dict("/Users/alasdair/OneDrive - University College London/Lenovo backup 181219/WellcomePhD/Year2/ukbiobank/ukb_dr_gwas/data/ukb_main_filter.txt")

data_dict_filter <- data_dict[1:10,]

ukb_df <- data.table::fread(
    "/Users/alasdair/OneDrive - University College London/Lenovo backup 181219/WellcomePhD/Year2/ukbiobank/ukb_dr_gwas/data/ukb_main_filter.txt",
    select = data_dict_filter$field_id_full_raw,
    colClasses = c('character'),
    na.strings = c("", "NA"),
    sep = "\t",
    data.table = TRUE,
    showProgress = TRUE,
  )
```

```{r}
ukb_codings <- data.table::fread(
    "https://biobank.ctsu.ox.ac.uk/~bbdatan/Codings.tsv",
    colClasses = c('character'),
    sep = "\t",
    na.strings = c("", "NA"),
    quote = " "
  )

ukb_data_dict <- data.table::fread(
    "https://biobank.ctsu.ox.ac.uk/~bbdatan/Data_Dictionary_Showcase.tsv",
    colClasses = c('character'),
    na.strings = c("", "NA"),
    sep = "\t",
  )

Data_Dictionary_Showcase <- readr::read_delim('https://biobank.ctsu.ox.ac.uk/~bbdatan/Data_Dictionary_Showcase.tsv', 
    "\t", escape_double = FALSE, trim_ws = TRUE, col_types = cols(.default = col_character()))

ukb_data_dict_filt_nested <- ukb_data_dict %>%
    dplyr::filter(FieldID %in% data_dict$FieldID) %>%
    dplyr::group_by(ValueType) %>%
    tidyr::nest()

extract_codings <-
    function(.ukb_data_dict_filt_nested,
             .valuetype) {
      .ukb_data_dict_filt_nested[(.ukb_data_dict_filt_nested$ValueType == .valuetype), ]$data[[1]]$Coding
    }

test <- extract_codings(ukb_data_dict_filt_nested, "Continuous")

test2 <- ukb_data_dict_filt_nested
```

```{r}
test_read_pheno <- read_pheno("/Users/alasdair/OneDrive - University College London/Lenovo backup 181219/WellcomePhD/Year2/ukbiobank/ukb_dr_gwas/data/ukb_main_filter.txt", pheno_data_dict = data_dict_filter)
```

